export const FEEDBACK_POST_REQUEST: string = 'FEEDBACK_POST_REQUEST'
export const FEEDBACK_POST_SUCCESS: string = 'FEEDBACK_POST_SUCCESS'
export const FEEDBACK_POST_FAIL: string = 'FEEDBACK_POST_FAIL'

export const GET_FEEDBACKS_REQUEST: string = 'GET_FEEDBACKS_REQUEST'
export const GET_FEEDBACKS_SUCCESS: string = 'GET_FEEDBACKS_SUCCESS'
export const GET_FEEDBACKS_FAIL: string = 'GET_FEEDBACKS_FAIL'
